Fix/docker network
unepwcmc/ProtectedPlanet pull request #777
Opened 2023-03-21 16:52 UTC by yuelongh

2023-03-21 17:13 UTC, yuelongh commented
updated docker compose file to accommodate for mac environment

2023-03-24 10:12 UTC, sergiomarrocoli approved these changes
looks good to me, and all works on my machine. good job!

Can you update the credentials in lastpass with the new ones required by these changes when this PR is merged please?

2023-03-24 11:37 UTC, pazolka commented
@sergiomarrocoli waiting for feedback from Romoke

2023-08-23 08:53 UTC, leonardow-unep-wcmc requested changes
Need to change the port setting, otherwise it doesn't work on Jenkins.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "5432:5432"
Please change to "5432" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "6379:6379"
Please change to "6379" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "9200:9200"
Please change to "9200" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "5601:5601"
Please change to "5601" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "3035:3035"
Please change to "3035" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "9292:9292"
Please change to "9292" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2023-08-23 08:53 UTC, leonardow-unep-wcmc commented on docker-compose.yml
> +      - "3000:3000"
Please change to "3000" (without host port), so it won't conflict with host port. This is Jenkins test, no one will connect from the host.

2025-02-03 06:00 UTC, closed without merging